# Generated by Django 3.0.5 on 2021-04-24 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('duration', models.IntegerField()),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2021, 4, 24, 15, 54, 15, 730379))),
            ],
        ),
    ]
