# Generated by Django 3.0.5 on 2021-04-24 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0002_auto_20210424_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=400)),
                ('duration', models.IntegerField()),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2021, 4, 24, 18, 42, 45, 966816))),
                ('host', models.CharField(default='', max_length=100)),
                ('participants', models.CharField(max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 18, 42, 45, 965817)),
        ),
    ]
